import type { Metadata } from "next";
import "./globals.css";
import * as React from "react";

export const metadata: Metadata = {
  title: "Calendly App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return children as React.JSX.Element;
}
